<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4f5ea5e517790b8f6a3296632b3b68ac
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'Instar\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Instar\\' => 
        array (
            0 => __DIR__ . '/../..' . '/vendor/instar',
        ),
    );

    public static $prefixesPsr0 = array (
        'S' => 
        array (
            'Slim' => 
            array (
                0 => __DIR__ . '/..' . '/slim/slim',
            ),
        ),
        'R' => 
        array (
            'Rain' => 
            array (
                0 => __DIR__ . '/..' . '/rain/raintpl/library',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4f5ea5e517790b8f6a3296632b3b68ac::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4f5ea5e517790b8f6a3296632b3b68ac::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit4f5ea5e517790b8f6a3296632b3b68ac::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
